polling/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('administrator/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls' #Add namespace to the URLconf
#If you have multiple apps which can have view functions with the same name,
#then in order to refer to a particular url/route from WITHIN a template,
#we need to be able to differentiate between the views with the same name.
#This is done with namespacing i.e. adding an app_name variable in the app level urls.py
#and also adding <app_name> : route name in the url template tag in the template

urlpatterns = [
path('', views.index, name = 'index'),
path('<int:question_id>/', views.detail, name = 'detail'),
path('<int:question_id>/results/', views.results, name = 'resultwa'),
path('<int:question_id>/vote/',views.vote, name = 'vote'),
path('chart/<int:question_id>/',views.plot_chart,name = 'chart'),
path('data/',views.return_data, name = 'json-data'),
path('ajax/',views.sample_ajax, name = 'sample-ajax'),
path('api/data/<int:question_id>/',views.return_chart_data, name = 'get-chart-data'),
]

#The name argument serves as an alias for the route url so that when 
#a url has to be written in a template, it doesnt need to be hard-coded
#i.e. we wont need to write: path/<arg>/ but can just use the value of
#the name variable to refer to that route.


#The part between the angular brackets< > is captured as argument, and then passed
#to the matched view function.

#A view function must return either an HttpResponse object or an exception

polls/models.py
from django.db import models

# Create your models here.
#2 models - Question(has question text and publication date)
# and Choice(option text and vote tally)

#Each Choice is associated with a Question

#EAch model has a number of class variables that represent a database field in the model
class Question(models.Model): #A model class must inherit from Django's Model superclass
	question_text = models.CharField(max_length = 200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

class Choice(models.Model):
	question = models.ForeignKey(Question,on_delete = models.CASCADE)
	#On Deleting a question, delete all the corresponding choices as well
	choice_text = models.CharField(max_length = 200)
	votes = models.IntegerField(default = 0)

	def __str__(self):
		return self.choice_text

#The two models have a many-to-one relationship: many Choice model class
#instances map to a single Question class instance(but not the other way aroung)


#Using the models defined here, Django creates a database schema for the
#application, creates a table for each model and allows the user to 
#manipulate the actual persistent data via the ORM. 


#Migrations are python files stored in the project which record what
#changes are to be made to the database schema. THis can include
#adding new fields, removing fields/constraints while developing the project
#make migrations command creates the migrations for the latest changes
#migrate command executes these changes.

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect,JsonResponse

from django.core import serializers
#The serialization framework is to serialize Django models/model objects

from django.shortcuts import render,get_object_or_404
from django.template import loader
from django.urls import reverse

from .models import Choice, Question
# Create your views here.

def index(request):
	#print(type(request))
	#return HttpResponse("Hello World. This is the index page of the polling app.")
	latest_questions = Question.objects.order_by('-pub_date')[:5]
	output = '\n '.join([q.question_text for q in latest_questions])
	#return HttpResponse(output)
	template = loader.get_template('polls/index.html')
	context = {'latest_questions' : latest_questions} #Data to be passed to template. Generally put in a 'context' dictionary
	return HttpResponse(template.render(context,request))


#Instead of directly returning an HTTP response from a view function,
#the data to be returned can be passed to a template which renders that
#data ro return a customized page.


#4 views in the polling app:
#An index page to display the latest questions, A detail page
#that shows a question with a form to vote
#Results page to display results for a question
#Vote action: Handles voting for a particular choice in a particular question

#The views need to be registered to a route in the URLConf (app level urls.py)

def detail(request,question_id):
	#return HttpResponse(f"You're looking at question {question_id}:")
	#Make DB call to fetch the question with given id
	
	try:
		question = Question.objects.get(id = question_id)		
	except Question.DoesNotExist:
		raise Http404("Question doesnt exist")
	else:
		#return HttpResponse(f"You're looking at question {question_id}: {question.question_text}")
		return render(request,'polls/detail.html',{'question' : question})
	#A shortcut for this routine of "Fetch an object from DB and return it or return a 404 if object doesnt exist"
	#is to use the get_object_or_404 function


def results(request,question_id):
	#return HttpResponse(f"Results of the question {question_id}")
	question = get_object_or_404(Question,pk = question_id)
	return render(request,'polls/results.html',{'question' : question})

def vote(request,question_id): #A POST request comes in to the corresponding route
	#return HttpResponse(f"Voting on the question {question_id}")
	question = get_object_or_404(Question,pk = question_id)
	try:
		selected_choice = question.choice_set.get(pk = request.POST['choice'])
	except (KeyError,Choice.DoesNotExist):
		#Redisplay the question voting form
		return render(request,'polls/detail.html',{'question':question,
			'error_message':'You didnt select a choice'})
	else:
		selected_choice.votes += 1
		selected_choice.save() #Update the value in DB
		return HttpResponseRedirect(reverse('polls:index'))

def plot_chart(request,question_id):
	return render(request,'polls/graphresult.html',{'q' : question_id})

def return_chart_data(request,question_id):
	question = Question.objects.get(pk = question_id)
	choices = question.choice_set.all()
	choice_data = {c.choice_text : c.votes for c in choices}
	return JsonResponse({"question": question.question_text,"choices" : choice_data})


#Sample routes for making AJAX call and getting back some data:

def return_data(request):
	#return JSON data for use by an AJAX call
	data = {'name':'Mudit','age':22}
	#serialized_data = serializers.serialize('json',data)
	#print(type(serialized_data))
	#return serialized_data
	return JsonResponse(data)

def sample_ajax(request):
	#This view function simply renders a template which makes an 
	#AJAX call to another route to get some JSON data
	return render(request,'polls/simple_ajax.html',{})

polls/templates/polls/chart.html
<!DOCTYPE html>
<html>
<head>
	<title>Getting started with Chart.Js</title>
</head>
<body>
	<canvas id = "myChart"> </canvas>
	<script src = "https://cdn.jsdelivr.net/npm/chart.js@2.8.0"> </script>

	<script> 
		var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
    // The type of chart we want to create
    type: 'bar',

    // The data for our dataset
    data: {
        labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
        datasets: [{
            label: 'My First dataset',
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: [0, 10, 5, 2, 20, 30, 45]
        }]
    },

    // Configuration options go here
    options: {}
});

	</script>

</body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<h2> {{ question.question_text }} </h2>
	{% if error_message %} <p> <strong> {{ error_message }} </strong> </p> {% endif %}
	<form action = "{% url 'polls:vote' question.id %}" method = "post">
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type = "radio" name = "choice" id = "choice{{ forloop.counter }}" value = "{{ choice.id }}">
			<label for = "choice{{ forloop.counter }}"> {{ choice.choice_text }} </label> <br>
		{% endfor %}
		<input type = "submit" value = "Vote">
	</form>


<!-- when somebody selects one of the radio buttons and submits the form, it’ll send the POST data choice=# where # is the choicce ID of the selected choice i.e. the value attribute for the selected radio button

On submitting the form, a POST request is made to vote route in the polls app
-->

</body>
</html>

polls/templates/polls/graphresult.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<canvas id = "myChart"> </canvas>
	<script src = "https://cdn.jsdelivr.net/npm/chart.js@2.8.0"> </script>

	<!-- Making the AJAX call -->
	<script type = "text/javascript">
		var http = new XMLHttpRequest();
		var result = true
		http.onreadystatechange = function() {
			if (http.readyState == XMLHttpRequest.DONE) {
					if (http.status == 200) {
					console.log("Request completed:" + http.readyState)
					var responseData = JSON.parse(http.responseText)
					setParams(responseData)
				} else
					result = false
			}
		}
		console.log("readyState value is:" + http.readyState)
		http.open('GET','http://localhost:8000/polls/api/data/{{ q }}/');
		http.send();
		
		if (result == false) {
			var p = document.createElement("p")
			p.innerHTML = "Unable to render graph"
			var link = document.createElement("a")
			link.setAttribute('href',"{% url 'polls:index' %}")
			link.innerHTML = "Go to index page"
			p.appendChild(link)
			document.body.appendChild(p)
		}
		else {
			console.log("Here")
			function setParams(responseData) {
				var ctx = document.getElementById('myChart').getContext('2d');
				var chart = new Chart(ctx, {
    	// The type of chart we want to create
    	type: 'bar',

    	// The data for our dataset
    	data: {
        	labels: Object.keys(responseData.choices),
        	datasets: [{
            label: responseData.question,
            backgroundColor: 'rgb(255, 99, 132)',
            borderColor: 'rgb(255, 99, 132)',
            data: Object.values(responseData.choices)
        }]
    	},

    	// Configuration options go here
    	options: {}
			});
		}
	}
</script>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<title>View the latest polls!</title>
</head>
<body>
	{% if latest_questions %}
		<ul>
			{% for question in latest_questions %} 
				{{ question.question_text }} <br> 
				<li> <a href = "{% url 'polls:detail' question.id %}"> Vote !</a> </li>  

				<li> <a href = "{% url 'polls:chart' question.id %}"> View current results! </a> </li>	
				<br>
			{% endfor %}
		</ul>
	{% else %}
		<p> No polls are available </p>
	{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
	<title>Voting results</title>
</head>
<body>
	<h1> {{ question.question_text }} </h1>
	<ul> 
		{% for choice in question.choice_set.all %}
			<li> {{ choice.choice_text }} -- {{ choice.votes }} </li>
		{% endfor %}
	</ul>

<a href = "{% url 'polls:detail' question.id %}"> Vote again? </a>
</body>
</html>

polls/templates/polls/simple_ajax.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<p id = "content-holder"> </p>
	<script>
		var httpreq = new XMLHttpRequest();
		httpreq.onreadystatechange = function() {
			if (httpreq.readyState == XMLHttpRequest.DONE) {
				if (httpreq.status == 200) {
					var data = JSON.parse(httpreq.responseText)
					console.log(data);
					document.getElementById("content-holder").innerHTML = "Name is: " + data.name + " and age is: " + data.age;
				} else
				document.getElementById("content-holder").innerHTML = "No reply."
			}
		}
		httpreq.open('GET','http://localhost:8000/polls/data/');
		httpreq.send();
	</script>

</body>
</html>